// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto/v1alpha1/auth/oauth2.proto

package auth

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ApplicationCreateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ApplicationCreateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ApplicationCreateRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ApplicationCreateRequestMultiError, or nil if none found.
func (m *ApplicationCreateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ApplicationCreateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ApplicationCreateRequestMultiError(errors)
	}

	return nil
}

// ApplicationCreateRequestMultiError is an error wrapping multiple validation
// errors returned by ApplicationCreateRequest.ValidateAll() if the designated
// constraints aren't met.
type ApplicationCreateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ApplicationCreateRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ApplicationCreateRequestMultiError) AllErrors() []error { return m }

// ApplicationCreateRequestValidationError is the validation error returned by
// ApplicationCreateRequest.Validate if the designated constraints aren't met.
type ApplicationCreateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ApplicationCreateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ApplicationCreateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ApplicationCreateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ApplicationCreateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ApplicationCreateRequestValidationError) ErrorName() string {
	return "ApplicationCreateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ApplicationCreateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sApplicationCreateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ApplicationCreateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ApplicationCreateRequestValidationError{}

// Validate checks the field values on ApplicationCreateResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ApplicationCreateResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ApplicationCreateResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ApplicationCreateResponseMultiError, or nil if none found.
func (m *ApplicationCreateResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ApplicationCreateResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ApplicationCreateResponseMultiError(errors)
	}

	return nil
}

// ApplicationCreateResponseMultiError is an error wrapping multiple validation
// errors returned by ApplicationCreateResponse.ValidateAll() if the
// designated constraints aren't met.
type ApplicationCreateResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ApplicationCreateResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ApplicationCreateResponseMultiError) AllErrors() []error { return m }

// ApplicationCreateResponseValidationError is the validation error returned by
// ApplicationCreateResponse.Validate if the designated constraints aren't met.
type ApplicationCreateResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ApplicationCreateResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ApplicationCreateResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ApplicationCreateResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ApplicationCreateResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ApplicationCreateResponseValidationError) ErrorName() string {
	return "ApplicationCreateResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ApplicationCreateResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sApplicationCreateResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ApplicationCreateResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ApplicationCreateResponseValidationError{}
